baseURL: https://options.nix-darwin.org/
languageCode: en-us
title: Nix Darwin - Option Search
theme: extranix-options-search

params:
  release_current_stable: nix-darwin-24.11
  releases:
    - name: unstable
      value: master
    - name: 24.11 (stable)
      value: nix-darwin-24.11

  release_switch_title: Nix Darwin Release

  custom_head_scripts: ""
  custom_header_tags: <div id="eadiv" data-ea-publisher="extranixcom" data-ea-type="text"></div>

  footer_credits_line: |
    Powered by the <a href="https://nix-darwin.org/">Nix Darwin</a> |
    <a href="https://github.com/mipmip/home-manager-option-search#credits">Credits</a> |
    <a href="https://nix-darwin.org/">Nix Darwin Documentation</a>

  footer_copyright_line: |
    Made with ❤️ by <a href="https://github.com/mipmip">Pim Snel</a>, supported by <a href="https://github.com/orzklv">Orzklv</a> - © 2025

  logo: images/nix-darwin-options.png

  github:
    repo: options
    user: nix-darwin
    show_count: true
    show_text: true

  main_menu:
    - name: Nix&nbsp;Darwin&nbsp;Documentation
      url: https://nix-darwin.org/
      icon_class: fa fa-book

    - name: Source
      url: https://github.com/nix-darwin/options
      icon_class: fa fa-github

markup:
  goldmark:
    renderer:
      unsafe: true
