name = 'Nix Darwin Options'
license = 'MIT'
licenselink = 'https://github.com/mipmip/hugo-theme-extranix-options-search/blob/main/LICENSE'
description = 'Theme which implements a nix modules options search machine.'

# The home page of the theme, where the source can be found
homepage = 'mipmip/hugo-theme-extranix-options-search'

# If you have a running demo of the theme
demosite = 'https://home-manager-options.extranix.com/'

# Taxonomy terms
tags = ['docs']
features = ['fast JavaScript search engine', 'Made for Nix Modules System']

[author]
name = 'Pim Snel'
homepage = 'extranix.com'
