name: "Parse and Deploy CI"
on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix on da machine
        uses: DeterminateSystems/nix-installer-action@main

      - name: Extract Options Master (unstable)
        run: ./scripts/build_and_parse_hm_options.rb

      - name: Update gitignore
        run: echo result > .gitignore

      - name: Extract Options Release-24.11 (stable)
        env:
          ND_RELEASE: nix-darwin-24.11
        run: ./scripts/build_and_parse_hm_options.rb

      - name: Extract Options Release-25.05 (stable)
        env:
          ND_RELEASE: nix-darwin-25.05
        run: ./scripts/build_and_parse_hm_options.rb

      - name: Build Hugo
        run: nix run nixpkgs#hugo -- --minify

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
